# Generated by Django 3.2.9 on 2022-07-04 11:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Carousel Data',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('option', models.CharField(max_length=30)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQs_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQs_CategoryType', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'FAQs Category',
                'ordering': ['FAQs_CategoryType'],
            },
        ),
        migrations.CreateModel(
            name='Footer_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Footer_Links_Title', models.CharField(max_length=100)),
                ('Footer_Links_Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Footer Links',
                'ordering': ['Footer_Links_Title'],
            },
        ),
        migrations.CreateModel(
            name='FooterMenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterMenuItems_Name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Footer Menu Items',
                'ordering': ['FooterMenuItems_Name'],
            },
        ),
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsAndEvents_HeadingName', models.CharField(max_length=100)),
                ('NewsAndEvents_CreationDate', models.DateTimeField(auto_now=True)),
                ('NewsAndEvents_UpdatedDate', models.DateTimeField(auto_now_add=True)),
                ('NewsAndEvents_Link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'News And Events',
                'ordering': ['NewsAndEvents_HeadingName'],
            },
        ),
        migrations.CreateModel(
            name='Resources_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resources_CategoryType', models.CharField(max_length=100)),
                ('Resources_Cat_Status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Resources Category',
                'ordering': ['Resources_CategoryType'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_Name', models.CharField(max_length=100)),
                ('Services_Description', models.CharField(max_length=300)),
                ('Services_links', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['Services_Name'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStories_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuccessStories_CategoryType', models.CharField(max_length=100)),
                ('SuccessStories_Cat_Status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Success Stories Category',
                'ordering': ['SuccessStories_CategoryType'],
            },
        ),
        migrations.CreateModel(
            name='Tools_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tools_CategoryType', models.CharField(max_length=100)),
                ('Tools_Cat_Status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tools Category',
                'ordering': ['Tools_CategoryType'],
            },
        ),
        migrations.CreateModel(
            name='Tools_Searched_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tools_Searched_Title_Name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Tools Searched Title Name',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TopMenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopMenuItems_Name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Top Menu Items',
                'ordering': ['TopMenuItems_Name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=60)),
                ('password', models.CharField(max_length=300)),
                ('Confirm_password', models.CharField(max_length=300)),
                ('phone', models.IntegerField(default=None)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToolsData_HeadingName', models.CharField(max_length=100)),
                ('ToolsData_Description', ckeditor.fields.RichTextField()),
                ('ToolsData_fileSize', models.CharField(default='', max_length=30)),
                ('ToolsData_VersionNumber', models.IntegerField()),
                ('ToolsData_UploadSupportDocument', models.FileField(blank=True, null=True, upload_to='Localisation_App/ToolsDocument')),
                ('ToolsData_UploadToolCode', models.FileField(blank=True, null=True, upload_to='Localisation_App/ToolsCode')),
                ('ToolsData_UploadedDate', models.DateTimeField(auto_now_add=True)),
                ('ToolsData_LastUpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('ToolsData_DownloadCounter', models.IntegerField()),
                ('ToolsData_CategoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.tools_category')),
            ],
            options={
                'verbose_name_plural': 'Tools Data',
                'ordering': ['ToolsData_HeadingName'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuccessStories_TitleName', models.CharField(max_length=100)),
                ('SuccessStories_Link', models.URLField(max_length=100)),
                ('SuccessStories_Description', ckeditor.fields.RichTextField()),
                ('SuccessStories_CreationDate', models.DateTimeField(auto_now_add=True)),
                ('SuccessStories_PublishedDate', models.DateTimeField(auto_now_add=True)),
                ('SuccessStories_LastUpdatedDate', models.DateTimeField(auto_now=True)),
                ('SuccessStories_PublishedStatus', models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='Unpublished', max_length=20)),
                ('SuccessStories_Upload_Image_1', models.ImageField(blank=True, null=True, upload_to='Localisation_App/Images')),
                ('SuccessStories_Upload_Image_2', models.ImageField(blank=True, null=True, upload_to='Localisation_App/Images')),
                ('SuccessStories_Upload_Image_3', models.ImageField(blank=True, null=True, upload_to='Localisation_App/Images')),
                ('SuccessStories_Upload_Image_4', models.ImageField(blank=True, null=True, upload_to='Localisation_App/Images')),
                ('SuccessStories_Upload_Image_5', models.ImageField(blank=True, null=True, upload_to='Localisation_App/Images')),
                ('SuccessStories_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.successstories_category')),
            ],
            options={
                'verbose_name_plural': 'Success Stories',
                'ordering': ['SuccessStories_TitleName'],
            },
        ),
        migrations.CreateModel(
            name='ResourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResourceData_HeadingName', models.CharField(max_length=100)),
                ('ResourceData_Description', ckeditor.fields.RichTextField()),
                ('ResourceData_fileSize', models.CharField(default='', max_length=30)),
                ('ResourceData_VersionNumber', models.IntegerField()),
                ('ResourceData_UploadSupportDocument', models.FileField(blank=True, null=True, upload_to='Localisation_App/ResourceDataDocument')),
                ('ResourceData_UploadResourceCode', models.FileField(blank=True, null=True, upload_to='Localisation_App/ResourceData')),
                ('ResourceData_UploadedDate', models.DateTimeField(auto_now_add=True)),
                ('ResourceData_LastUpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('ResourceData_DownloadCounter', models.IntegerField()),
                ('ResourceData_CategoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.resources_category')),
            ],
            options={
                'verbose_name_plural': 'Resource Data',
                'ordering': ['ResourceData_HeadingName'],
            },
        ),
        migrations.CreateModel(
            name='Footer_Links_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Footer_Links_Info_SubTitle', models.CharField(max_length=100)),
                ('Footer_Links_Info_SubContent', ckeditor.fields.RichTextField()),
                ('Footer_Links_Info_MainTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.footer_links')),
            ],
            options={
                'verbose_name_plural': 'Footer Info',
                'ordering': ['Footer_Links_Info_SubTitle'],
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQs_Question', models.CharField(max_length=1000)),
                ('FAQs_Answer', ckeditor.fields.RichTextField()),
                ('FAQs_CategoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.faqs_category')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['FAQs_Question'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_HeadingName', models.CharField(max_length=100)),
                ('Article_Description', ckeditor.fields.RichTextField()),
                ('Article_Image', models.ImageField(null=True, upload_to='Localisation_App/Images')),
                ('Article_CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Article_LastUpdatedDate', models.DateTimeField(auto_now=True)),
                ('Article_PublishedDate', models.DateTimeField(auto_now_add=True)),
                ('Article_PublishedStatus', models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='Unpublished', max_length=20)),
                ('Article_ContentGivenBy', models.CharField(max_length=100)),
                ('Article_MenuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.topmenuitems')),
            ],
            options={
                'verbose_name_plural': 'Article',
                'ordering': ['Article_HeadingName'],
            },
        ),
    ]
