# Generated by Django 3.2.9 on 2022-07-18 05:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Localisation_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='admin_remark',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='quotation_generated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('INPROCESS', 'INPROCESS')], default='PENDING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='total_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='translation_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='url',
            field=models.URLField(max_length=20, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
