# Generated by Django 3.2.9 on 2022-07-14 09:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpanelledAgencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Empanelled Agencies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='GuidelinceForIndianGovWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Guidelince For Indian Gov Website',
            },
        ),
        migrations.CreateModel(
            name='TranslationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('language', models.CharField(max_length=200)),
                ('website_type', models.CharField(max_length=200, null=True)),
                ('delivery_date', models.DateField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Translation Quote',
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('userregistration_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('userregistration_first_name', models.CharField(max_length=60)),
                ('userregistration_middle_name', models.CharField(max_length=60)),
                ('userregistration_last_name', models.CharField(max_length=60)),
                ('userregistration_username', models.CharField(blank=True, max_length=60, null=True)),
                ('userregistration_email_field', models.EmailField(max_length=60)),
                ('userregistration_phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('userregistration_address', models.CharField(blank=True, max_length=200, null=True)),
                ('userregistration_password', models.CharField(max_length=30)),
                ('userregistration_confirm_password', models.CharField(max_length=30)),
                ('userregistration_active_status', models.BooleanField(default=False)),
                ('registration_User_Type', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization'), ('DomainExpert', 'DomainExpert')], default='Individual', max_length=50)),
                ('userregistration_registration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('userregistration_token', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Registration',
                'ordering': ['userregistration_first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='footermenuitems',
            options={'ordering': ['id'], 'verbose_name_plural': 'Footer Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='topmenuitems',
            options={'ordering': ['id'], 'verbose_name_plural': 'Top Menu Items'},
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='NewsAndEvents_Discription',
            field=models.CharField(default='null', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcedata',
            name='ResourceData_PublishedStatus',
            field=models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcedata',
            name='ResourceData_slug',
            field=models.SlugField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='SuccessStories_Cdac_Contribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='SuccessStories_Priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AddField(
            model_name='successstories_category',
            name='SuccessStories_Cat_Priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
        migrations.AddField(
            model_name='toolsdata',
            name='ToolsData_PublishedStatus',
            field=models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='successstories',
            name='SuccessStories_PublishedStatus',
            field=models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='successstories',
            name='SuccessStories_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.successstories_category'),
        ),
        migrations.CreateModel(
            name='EmpanelledAgenciesEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('empanelled_agencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.empanelledagencies', verbose_name='Empanelled Agency Name')),
            ],
            options={
                'verbose_name_plural': 'Empanelled Agencies Emails',
                'ordering': ['email'],
            },
        ),
    ]
