# Generated by Django 3.2.9 on 2022-07-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstories',
            name='SuccessStories_category',
        ),
    ]
