# Generated by Django 3.2.9 on 2022-07-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0003_successstories_successstories_category'),
    ]

    operations = [
    ]
