# Generated by Django 3.2.9 on 2022-07-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0003_alter_translationquote_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.userregistration'),
        ),
    ]
