# Generated by Django 3.2.9 on 2022-07-18 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0003_alter_translationquote_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator(), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
