# Generated by Django 3.2.9 on 2022-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0004_auto_20220704_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='SuccessStories_Cdac_Contribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
