# Generated by Django 3.2.9 on 2022-07-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0004_alter_translationquote_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
