# Generated by Django 3.2.9 on 2022-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0005_alter_translationquote_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='client_remark',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
