# Generated by Django 3.2.9 on 2022-07-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0006_auto_20220705_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmenuitems',
            name='Url_Path',
        ),
    ]
