# Generated by Django 3.2.9 on 2022-07-21 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0008_marketingsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='registration_User_Type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Organization', 'Organization'), ('DomainExpert', 'DomainExpert')], default='Individual', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='userregistration_first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='userregistration_last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='userregistration_middle_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='userregistration_phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
