# Generated by Django 3.2.9 on 2022-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0009_auto_20220705_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='userregistration_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
