# Generated by Django 3.2.9 on 2022-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0010_userregistration_userregistration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='userregistration_username',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
