# Generated by Django 3.2.9 on 2022-07-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0011_userregistration_userregistration_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ['userregistration_first_name'], 'verbose_name_plural': 'User Registration'},
        ),
    ]
