# Generated by Django 3.2.9 on 2022-07-06 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0012_alter_userregistration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='userregistration_phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
