# Generated by Django 3.2.9 on 2022-07-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0014_alter_userregistration_userregistration_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='SuccessStories_Priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], max_length=10, null=True),
        ),
    ]
