# Generated by Django 3.2.9 on 2022-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0017_successstories_category_successstories_cat_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelinceForIndianGovWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Guidelince For Indian Gov Website',
            },
        ),
        migrations.AlterField(
            model_name='successstories',
            name='SuccessStories_Priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='successstories_category',
            name='SuccessStories_Cat_Priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
    ]
