# Generated by Django 3.2.9 on 2022-07-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0018_auto_20220709_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationquote',
            name='delivery_date',
            field=models.DateField(auto_now=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='website_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
