# Generated by Django 3.2.9 on 2022-07-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0018_auto_20220709_1540'),
        ('Localisation_App', '0019_auto_20220709_1920'),
    ]

    operations = [
    ]
