# Generated by Django 3.2.9 on 2022-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0020_merge_0018_auto_20220709_1540_0019_auto_20220709_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='delivery_date',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
