# Generated by Django 3.2.9 on 2022-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0022_alter_successstories_successstories_publishedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedata',
            name='ResourceData_PublishedStatus',
            field=models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='toolsdata',
            name='ToolsData_PublishedStatus',
            field=models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='published', max_length=20),
        ),
    ]
