# Generated by Django 3.2.9 on 2022-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0023_auto_20220711_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='userregistration_token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
