# Generated by Django 3.2.9 on 2022-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0024_userregistration_userregistration_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpanelledAgencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Empanelled Agencies',
                'ordering': ['company_name'],
            },
        ),
    ]
