# Generated by Django 3.2.9 on 2022-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0024_userregistration_userregistration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='NewsAndEvents_Discription',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
