# Generated by Django 3.2.9 on 2022-07-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0025_empanelledagencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpanelledAgenciesEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('empanelled_agencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.empanelledagencies', verbose_name='Empanelled Agency Name')),
            ],
            options={
                'verbose_name_plural': 'Empanelled Agencies Emails',
                'ordering': ['email'],
            },
        ),
    ]
