# Generated by Django 3.2.9 on 2022-07-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0026_empanelledagenciesemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empanelledagencies',
            name='email_address',
        ),
    ]
