# Generated by Django 3.2.9 on 2022-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0027_alter_newsandevents_newsandevents_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='NewsAndEvents_Discription',
            field=models.CharField(max_length=5000),
        ),
    ]
