# Generated by Django 4.0.6 on 2022-07-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0027_remove_empanelledagencies_email_address'),
        ('Localisation_App', '0028_alter_newsandevents_newsandevents_discription'),
    ]

    operations = [
    ]
