# Generated by Django 3.2.9 on 2022-07-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0029_merge_20220713_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationQuoteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Translation Quote Language',
                'verbose_name_plural': 'TranslationQuoteLanguages',
            },
        ),
        migrations.AddField(
            model_name='translationquote',
            name='client_remark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='company_email',
            field=models.EmailField(default='xxx@xxx.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.translationquotelanguage', verbose_name='Language'),
        ),
    ]
