# Generated by Django 3.2.9 on 2022-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0029_merge_20220713_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
