# Generated by Django 3.2.9 on 2022-07-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0030_testslug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testslug',
            options={'ordering': ['Test_Title'], 'verbose_name_plural': 'Test_Title'},
        ),
    ]
