# Generated by Django 3.2.9 on 2022-07-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0030_auto_20220714_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationQuoteDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Translation Quote Domains',
            },
        ),
        migrations.AlterModelOptions(
            name='translationquotelanguage',
            options={'verbose_name': 'Translation Quote Language', 'verbose_name_plural': 'Translation Quote Languages'},
        ),
        migrations.RemoveField(
            model_name='translationquote',
            name='website_type',
        ),
        migrations.AddField(
            model_name='translationquote',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.translationquotedomain', verbose_name='domain'),
        ),
    ]
