# Generated by Django 3.2.9 on 2022-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0031_auto_20220714_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='domain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='TranslationQuoteDomain',
        ),
        migrations.DeleteModel(
            name='TranslationQuoteLanguage',
        ),
    ]
