# Generated by Django 3.2.9 on 2022-07-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0031_alter_testslug_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSlug',
        ),
        migrations.AddField(
            model_name='resourcedata',
            name='ResourceData_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
