# Generated by Django 3.2.9 on 2022-07-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0032_auto_20220714_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedata',
            name='ResourceData_slug',
            field=models.SlugField(blank=True, max_length=2000, null=True),
        ),
    ]
