# Generated by Django 3.2.9 on 2022-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0032_auto_20220714_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
