# Generated by Django 3.2.9 on 2022-07-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0033_alter_translationquote_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationquote',
            name='admin_remark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='application_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='quotation_generated_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INPROCESS', 'INPROCESS')], default='PENDING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='total_words',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='translation_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='translationquote',
            name='uer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.user', verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='translationquote',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
