# Generated by Django 3.2.9 on 2022-07-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0034_auto_20220714_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquote',
            name='uer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Localisation_App.userregistration', verbose_name='User Id'),
        ),
    ]
