# Generated by Django 3.2.9 on 2022-07-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0035_alter_toolsdata_toolsdata_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolsdata',
            old_name='ToolsData_slug',
            new_name='ToolsDatat_slug',
        ),
    ]
