# Generated by Django 3.2.9 on 2022-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0036_rename_toolsdata_slug_toolsdata_toolsdatat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsdata',
            name='ToolsDatat_slug',
            field=models.SlugField(blank=True, max_length=2000, null=True),
        ),
    ]
