# Generated by Django 3.2.9 on 2022-07-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0045_alter_translationquote_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationquote',
            name='submission_date',
        ),
    ]
