# Generated by Django 3.2.9 on 2022-07-14 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation_App', '0046_remove_translationquote_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationquote',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 14, 18, 40, 29, 273640)),
        ),
    ]
